# Custom Language File for Launcher Customizer

[ejs.app]
title = "GalaxyQuest"

[ejs.landing]
mediaGitHubURL = "https://github.com/mc-galaxyquest/launcher"
mediaTwitterURL = "https://twitter.galaxyquest.fr/"
mediaInstagramURL = "https://instagram.galaxyquest.Fr/"
mediaYouTubeURL = "https://youtube.galaxyquest.fr/"
mediaDiscordURL = "https://discord.gg/galaxyquest"

[ejs.settings]
sourceGithubLink = "https://github.com/mc-galaxyquest/launcher"
supportLink = "https://support.galaxyquest.fr"

[ejs.welcome]
welcomeHeader = "Rejoignez GalaxyQuest !"
welcomeDescription = "Galaxyquest est un serveur futuriste pvp-faction moddé sur le thème de l'espace. Rejoignez le serveur pour vous plonger dans l'aventure !"
welcomeDescCTA = "Faites décoler votre vaisseau saptial."
